site_name: Ares SC2

theme:
  name: material
  favicon: assets/favicon.ico
  palette:
  - scheme: default
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: blue grey
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github-alt
  language: en

repo_name: ares-sc2
repo_url: https://github.com/AresSC2/ares-sc2

nav:
  - Start here: index.md
  - Tutorials:
      - tutorials/index.md
      - Assigning Unit Roles: tutorials/assigning_unit_roles.md
      - Build Runner: tutorials/build_runner.md
      - Chat Debug: tutorials/chat_debug.md
      - Combat Maneuver Example: tutorials/combat_maneuver_example.md
      - Creating Custom Behaviors: tutorials/custom_behaviors.md
      - Config File: tutorials/config_file.md
      - Gotchas: tutorials/gotchas.md
      - Influence and Pathing: tutorials/influence_and_pathing.md
      - Managing Production: tutorials/managing_production.md
      - Migrating from python-sc2: tutorials/migrating.md
      - Unit Squads and Group Behaviors: tutorials/unit_squads_group_behaviors.md
  - API Reference:
      - api_reference/index.md
      - Behaviors:
          - api_reference/behaviors/index.md
          - Individual Combat Behaviors: api_reference/behaviors/combat_behaviors.md
          - Group Combat Behaviors: api_reference/behaviors/group_combat_behaviors.md
          - Macro Behaviors: api_reference/behaviors/macro_behaviors.md
      - api_reference/manager_mediator.md

  - Contributing:
      - contributing/index.md

markdown_extensions:
  - toc:
      baselevel: 1
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# to navigate with `/site` content correctly
use_directory_urls: false

plugins:
  - search
  - mkdocstrings:
      watch: [src]
      handlers:
        python:
          paths: [src]
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: false
            show_root_full_path: false
            heading_level: 2
            merge_init_into_class: true
            show_signature_annotations: false
            separate_signature: true
            show_root_toc_entry: false

extra_css:
  - stylesheets/extra.css
