FROM python:3.11-slim
MAINTAINER rasper

USER root
WORKDIR /root/

RUN dpkg --add-architecture i386

# Update system and install packages in a single RUN to reduce layers
RUN apt-get update && \
    apt-get upgrade --assume-yes --quiet=2 && \
    apt-get install --assume-yes --no-install-recommends --no-show-upgraded \
    wget \
    unzip \
    git  \
    make \
    gcc \
    tree \
    gpg \
    procps \
    lsof \
    apt-transport-https \
    libgtk2.0-dev \
    software-properties-common \
    dirmngr \
    gpg-agent \
    g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Upgrade pip and install pip-install requirements
RUN python3 -m pip install --upgrade pip pipenv

RUN python3 -m pip install poetry

# Create a symlink for the maps directory
RUN ln -s /root/StarCraftII/Maps /root/StarCraftII/maps

ADD . /root/ares-sc2

# then to the actual working directory
WORKDIR /root/ares-sc2

RUN mv tests/maps/* ~/StarCraftII/maps

RUN poetry install


ENTRYPOINT [ "/bin/bash" ]
