FROM python:3.11-slim
MAINTAINER rasper

USER root
WORKDIR /root/

RUN dpkg --add-architecture i386

# Configure apt and install packages
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update -y && \
    apt-get install -y apt-utils && \
    apt-get upgrade -y --quiet=2 && \
    apt-get install -y --no-install-recommends \
    wget \
    unzip \
    git  \
    make \
    gcc \
    tree \
    gpg \
    procps \
    lsof \
    apt-transport-https \
    libgtk2.0-dev \
    software-properties-common \
    dirmngr \
    gpg-agent \
    g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and uncompress StarCraftII from https://github.com/Blizzard/s2client-proto#linux-packages
RUN wget -q 'http://blzdistsc2-a.akamaihd.net/Linux/SC2.4.10.zip' \
    && unzip -P iagreetotheeula SC2.4.10.zip \
    && rm SC2.4.10.zip

# Upgrade pip and install pip-install requirements
RUN python3 -m pip install --upgrade pip pipenv

RUN python3 -m pip install poetry

# Create a symlink for the maps directory
RUN ln -s /root/StarCraftII/Maps /root/StarCraftII/maps

ADD . /root/ares-sc2

# then to the actual working directory
WORKDIR /root/ares-sc2

RUN mv tests/maps/* ~/StarCraftII/maps

RUN poetry install

ENTRYPOINT [ "/bin/bash" ]