MOCK_CONFIG: dict = {
    "UseData": False,
    "Debug": False,
    "GameStep": 2,
    "DebugGameStep": 2,
    "DebugOptions": {
        "ActiveGrid": "Ground",
        "ChatDebug": True,
        "DebugSpawn": False,
        "ShowPathingCost": False,
        "ShowBuildingFormation": False,
        "ResourceDebug": False,
    },
    "Chat": {"Enabled": True, "AiarenaTags": True, "FlankChat": True},
    "Distances": {
        "FlyingEnemyNearBases": 20.0,
        "GroundEnemyNearBases": 15.0,
        "GroundEnemyLeavingBases": 24.0,
        "FlyingEnemyLeavingBases": 22.0,
    },
    "Building": {"CancelOrder": 18},
    "Mining": {
        "MineralBoost": True,
        "MineralStacking": True,
        "VespeneBoost": False,
        "BoostBackToTownHall": True,
        "GeyserDistanceFactor": 1.05,
        "GeyserThreshold": 0.05,
        "MineralDistanceFactor": 1.25,
        "TownhallDistanceFactor": 1.08,
    },
    "Pathing": {
        "RangeBuffer": 4.0,
        "EffectsRangeBuffer": 1.0,
        "CostMultiplier": 1,
        "Effects": {
            "BlindingCloud": {"Cost": 300, "Range": 3.5},
            "CorrosiveBile": {"Cost": 100, "Range": 3.0},
            "LiberatorZone": {"Cost": 500, "Range": 6},
            "LurkerSpine": {"Cost": 600, "Range": 1},
            "Nuke": {"Cost": 1000, "Range": 8},
            "ParasiticBomb": {"Cost": 17.15, "Range": 4},
            "Storm": {"Cost": 600, "Range": 3.5},
        },
    },
    "Placement": {"WorkerOnRouteTimeout": 60.0},
}
