# this is how ares would read if from the yml file
# PLEASE DON'T EDIT THIS!
MOCK_BUILD_ORDER: list[str] = [
    "14 supply @ ramp",
    "16 barracks @ ramp",
    "16 gas",
    "0 reaper",
    "0 orbital",
    "19 expand",
    "20 supply @ ramp",
    "20 factory @ ramp",
    "21 marine",
    "22 gas",
    "23 barracksreactor",
    "23 barracks",
    "24 starport",
    "25 widowmine",
    "25 orbital",
    "27 widowmine",
    "29 medivac",
    "29 factorytechlab",
    "29 siegetank",
    "29 starporttechlab",
    "32 gas",
    "35 barracks",
    "40 raven",
]
