"""Mineral, gas, supply, and army values for units.

"""
from typing import Dict

from sc2.ids.unit_typeid import UnitTypeId as UnitID

# Zerg building data includes Drone cost
UNIT_DATA: Dict[UnitID, Dict] = {
    UnitID.SCV: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitID.MULE: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitID.MARINE: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 1},
    UnitID.MARAUDER: {"minerals": 100, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.REAPER: {"minerals": 50, "gas": 50, "supply": 1, "army_value": 1},
    UnitID.GHOST: {"minerals": 150, "gas": 125, "supply": 2, "army_value": 2},
    UnitID.HELLION: {"minerals": 100, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.HELLIONTANK: {"minerals": 100, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.WIDOWMINE: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.WIDOWMINEBURROWED: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.SIEGETANK: {"minerals": 150, "gas": 125, "supply": 3, "army_value": 3},
    UnitID.SIEGETANKSIEGED: {"minerals": 150, "gas": 125, "supply": 3, "army_value": 3},
    UnitID.CYCLONE: {"minerals": 150, "gas": 100, "supply": 3, "army_value": 3},
    UnitID.THOR: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitID.THORAP: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitID.VIKINGASSAULT: {"minerals": 150, "gas": 75, "supply": 2, "army_value": 2},
    UnitID.VIKINGFIGHTER: {"minerals": 150, "gas": 75, "supply": 2, "army_value": 2},
    UnitID.MEDIVAC: {"minerals": 100, "gas": 100, "supply": 2, "army_value": 2},
    UnitID.LIBERATOR: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitID.LIBERATORAG: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitID.BANSHEE: {"minerals": 150, "gas": 100, "supply": 3, "army_value": 3},
    UnitID.RAVEN: {"minerals": 100, "gas": 200, "supply": 2, "army_value": 2},
    UnitID.BATTLECRUISER: {"minerals": 400, "gas": 300, "supply": 6, "army_value": 7},
    UnitID.POINTDEFENSEDRONE: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 1},
    UnitID.PROBE: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitID.ZEALOT: {"minerals": 100, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.SENTRY: {"minerals": 50, "gas": 100, "supply": 2, "army_value": 2},
    UnitID.STALKER: {"minerals": 125, "gas": 50, "supply": 2, "army_value": 2},
    UnitID.ADEPT: {"minerals": 100, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.ADEPTPHASESHIFT: {"minerals": 100, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.HIGHTEMPLAR: {"minerals": 50, "gas": 150, "supply": 2, "army_value": 2},
    UnitID.DARKTEMPLAR: {"minerals": 125, "gas": 125, "supply": 2, "army_value": 2},
    UnitID.ARCHON: {"minerals": 175, "gas": 275, "supply": 4, "army_value": 5},
    UnitID.OBSERVER: {"minerals": 25, "gas": 75, "supply": 1, "army_value": 0.25},
    UnitID.OBSERVERSIEGEMODE: {
        "minerals": 25,
        "gas": 75,
        "supply": 1,
        "army_value": 0.25,
    },
    UnitID.WARPPRISM: {"minerals": 200, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.WARPPRISMPHASING: {"minerals": 200, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.IMMORTAL: {"minerals": 275, "gas": 100, "supply": 4, "army_value": 4},
    UnitID.COLOSSUS: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitID.DISRUPTOR: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitID.DISRUPTORPHASED: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 3},
    UnitID.PHOENIX: {"minerals": 150, "gas": 100, "supply": 2, "army_value": 2},
    UnitID.VOIDRAY: {"minerals": 250, "gas": 150, "supply": 4, "army_value": 4},
    UnitID.ORACLE: {"minerals": 150, "gas": 150, "supply": 3, "army_value": 3},
    UnitID.TEMPEST: {"minerals": 250, "gas": 175, "supply": 5, "army_value": 5},
    UnitID.CARRIER: {"minerals": 350, "gas": 250, "supply": 6, "army_value": 8},
    UnitID.INTERCEPTOR: {"minerals": 15, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitID.MOTHERSHIP: {"minerals": 300, "gas": 300, "supply": 8, "army_value": 8},
    UnitID.LARVA: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.EGG: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.DRONE: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitID.DRONEBURROWED: {"minerals": 50, "gas": 0, "supply": 1, "army_value": 0.5},
    UnitID.QUEEN: {"minerals": 150, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.QUEENBURROWED: {"minerals": 150, "gas": 0, "supply": 2, "army_value": 2},
    UnitID.ZERGLING: {"minerals": 25, "gas": 0, "supply": 0.5, "army_value": 0.5},
    UnitID.ZERGLINGBURROWED: {
        "minerals": 25,
        "gas": 0,
        "supply": 0.5,
        "army_value": 0.5,
    },
    UnitID.BANELINGCOCOON: {"minerals": 25, "gas": 25, "supply": 0.5, "army_value": 1},
    UnitID.BANELING: {"minerals": 25, "gas": 25, "supply": 0.5, "army_value": 1},
    UnitID.BANELINGBURROWED: {
        "minerals": 25,
        "gas": 25,
        "supply": 0.5,
        "army_value": 1,
    },
    UnitID.ROACH: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.ROACHBURROWED: {"minerals": 75, "gas": 25, "supply": 2, "army_value": 2},
    UnitID.RAVAGER: {"minerals": 75 + 25, "gas": 75 + 25, "supply": 3, "army_value": 3},
    UnitID.RAVAGERBURROWED: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 3,
    },
    UnitID.RAVAGERCOCOON: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 3,
    },
    UnitID.HYDRALISK: {"minerals": 100, "gas": 50, "supply": 2, "army_value": 2},
    UnitID.HYDRALISKBURROWED: {
        "minerals": 100,
        "gas": 50,
        "supply": 2,
        "army_value": 2,
    },
    UnitID.LURKERMP: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 3,
    },
    UnitID.LURKERMPBURROWED: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 3,
    },
    UnitID.LURKERMPEGG: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 3,
    },
    UnitID.INFESTOR: {"minerals": 100, "gas": 150, "supply": 2, "army_value": 2},
    UnitID.INFESTEDTERRANSEGG: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.INFESTEDTERRAN: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.INFESTORTERRAN: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.INFESTORBURROWED: {
        "minerals": 100,
        "gas": 150,
        "supply": 2,
        "army_value": 2,
    },
    UnitID.SWARMHOSTMP: {"minerals": 100, "gas": 75, "supply": 3, "army_value": 3},
    UnitID.SWARMHOSTBURROWEDMP: {
        "minerals": 100,
        "gas": 75,
        "supply": 3,
        "army_value": 3,
    },
    UnitID.LOCUSTMP: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.5},
    UnitID.LOCUSTMPFLYING: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.5},
    UnitID.ULTRALISK: {"minerals": 300, "gas": 200, "supply": 6, "army_value": 6},
    UnitID.ULTRALISKBURROWED: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 6,
    },
    UnitID.OVERLORD: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0.1},
    UnitID.OVERLORDCOCOON: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0.1},
    UnitID.OVERLORDTRANSPORT: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.5,
    },
    UnitID.TRANSPORTOVERLORDCOCOON: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.1,
    },
    UnitID.OVERSEER: {"minerals": 150, "gas": 50, "supply": 0, "army_value": 0.5},
    UnitID.OVERSEERSIEGEMODE: {
        "minerals": 150,
        "gas": 50,
        "supply": 0,
        "army_value": 0.5,
    },
    UnitID.CHANGELING: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitID.CHANGELINGMARINE: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitID.CHANGELINGMARINESHIELD: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitID.CHANGELINGZEALOT: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitID.CHANGELINGZERGLING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitID.CHANGELINGZERGLINGWINGS: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.01,
    },
    UnitID.MUTALISK: {"minerals": 100, "gas": 100, "supply": 2, "army_value": 2},
    UnitID.CORRUPTOR: {"minerals": 150, "gas": 100, "supply": 2, "army_value": 2},
    UnitID.VIPER: {"minerals": 100, "gas": 200, "supply": 3, "army_value": 3},
    UnitID.BROODLORD: {
        "minerals": 150 + 150,
        "gas": 150 + 100,
        "supply": 4,
        "army_value": 6,
    },
    UnitID.BROODLORDCOCOON: {
        "minerals": 150 + 150,
        "gas": 150 + 100,
        "supply": 4,
        "army_value": 6,
    },
    UnitID.BROODLING: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.01},
    UnitID.COMMANDCENTER: {"minerals": 400, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.COMMANDCENTERFLYING: {
        "minerals": 400,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.ORBITALCOMMAND: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.ORBITALCOMMANDFLYING: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.PLANETARYFORTRESS: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 5,
    },
    UnitID.SUPPLYDEPOT: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.SUPPLYDEPOTLOWERED: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.REFINERY: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.BARRACKS: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.BARRACKSFLYING: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.ENGINEERINGBAY: {"minerals": 125, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.BUNKER: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 5},
    UnitID.MISSILETURRET: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 1},
    UnitID.AUTOTURRET: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 1},
    UnitID.SENSORTOWER: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.FACTORY: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.FACTORYFLYING: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.GHOSTACADEMY: {"minerals": 150, "gas": 50, "supply": 0, "army_value": 0},
    UnitID.ARMORY: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.STARPORT: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.STARPORTFLYING: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.FUSIONCORE: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitID.TECHLAB: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.BARRACKSTECHLAB: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.FACTORYTECHLAB: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.STARPORTTECHLAB: {"minerals": 125, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.REACTOR: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 0},
    UnitID.BARRACKSREACTOR: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 0},
    UnitID.FACTORYREACTOR: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 0},
    UnitID.STARPORTREACTOR: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 0},
    UnitID.NEXUS: {"minerals": 400, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.PYLON: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.ASSIMILATOR: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.GATEWAY: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.FORGE: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.PHOTONCANNON: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 3},
    UnitID.SHIELDBATTERY: {"minerals": 100, "gas": 0, "supply": 0, "army_value": 2},
    UnitID.WARPGATE: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.CYBERNETICSCORE: {"minerals": 150, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.TWILIGHTCOUNCIL: {"minerals": 150, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.ROBOTICSFACILITY: {
        "minerals": 200,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.STARGATE: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitID.TEMPLARARCHIVE: {"minerals": 150, "gas": 200, "supply": 0, "army_value": 0},
    UnitID.DARKSHRINE: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitID.ROBOTICSBAY: {"minerals": 150, "gas": 150, "supply": 0, "army_value": 0},
    UnitID.FLEETBEACON: {"minerals": 300, "gas": 200, "supply": 0, "army_value": 0},
    UnitID.ORACLESTASISTRAP: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 1},
    UnitID.HATCHERY: {"minerals": 300 + 50, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.EXTRACTOR: {"minerals": 25 + 50, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.SPAWNINGPOOL: {"minerals": 200 + 50, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.EVOLUTIONCHAMBER: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.SPINECRAWLER: {"minerals": 100 + 50, "gas": 0, "supply": 0, "army_value": 3},
    UnitID.SPINECRAWLERUPROOTED: {
        "minerals": 100 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 3,
    },
    UnitID.SPORECRAWLER: {"minerals": 75 + 50, "gas": 0, "supply": 0, "army_value": 3},
    UnitID.SPORECRAWLERUPROOTED: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 3,
    },
    UnitID.ROACHWARREN: {"minerals": 150 + 50, "gas": 0, "supply": 0, "army_value": 0},
    UnitID.BANELINGNEST: {
        "minerals": 100 + 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.INFESTATIONPIT: {
        "minerals": 150 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.LAIR: {"minerals": 450 + 50, "gas": 100, "supply": 0, "army_value": 0},
    UnitID.HIVE: {"minerals": 650 + 50, "gas": 250, "supply": 0, "army_value": 0},
    UnitID.HYDRALISKDEN: {
        "minerals": 100 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.LURKERDENMP: {
        "minerals": 150 + 50,
        "gas": 150,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.SPIRE: {"minerals": 200 + 50, "gas": 200, "supply": 0, "army_value": 0},
    UnitID.NYDUSNETWORK: {
        "minerals": 150 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.NYDUSCANAL: {"minerals": 50, "gas": 50, "supply": 0, "army_value": 7},
    UnitID.ULTRALISKCAVERN: {
        "minerals": 150 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.GREATERSPIRE: {
        "minerals": 300 + 50,
        "gas": 350,
        "supply": 0,
        "army_value": 0,
    },
    UnitID.CREEPTUMOR: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.1},
    UnitID.CREEPTUMORBURROWED: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.1,
    },
    UnitID.CREEPTUMORQUEEN: {"minerals": 0, "gas": 0, "supply": 0, "army_value": 0.1},
    UnitID.REFINERYRICH: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0.0},
    UnitID.ASSIMILATORRICH: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0.0},
    UnitID.EXTRACTORRICH: {"minerals": 75, "gas": 0, "supply": 0, "army_value": 0.0},
}
