"""Mineral, gas, supply, and army values for units."""

from sc2.ids.unit_typeid import UnitTypeId

# army_value = (((minerals / 0.9) + gas) * supply) / 50
# with some edits where appropriate
# Zerg building data includes Drone cost
UNIT_DATA: dict[UnitTypeId, dict] = {
    # these first 2 entries are rich vespene buildings?
    # on patch 5.0.14 AIE maps
    UnitTypeId.SIEGETANKMENGSKACGLUESCREENDUMMY: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.MEDIVACMENGSKACGLUESCREENDUMMY: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.SCV: {
        "minerals": 50,
        "gas": 0,
        "supply": 1,
        "army_value": 1.111,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.MULE: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.MARINE: {
        "minerals": 50,
        "gas": 0,
        "supply": 1,
        "army_value": 1.111,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.MARAUDER: {
        "minerals": 100,
        "gas": 25,
        "supply": 2,
        "army_value": 5.444,
        "radius": 0.5625,
        "flying": False,
    },
    UnitTypeId.REAPER: {
        "minerals": 50,
        "gas": 50,
        "supply": 1,
        "army_value": 2.111,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.GHOST: {
        "minerals": 150,
        "gas": 125,
        "supply": 2,
        "army_value": 11.667,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.HELLION: {
        "minerals": 100,
        "gas": 0,
        "supply": 2,
        "army_value": 4.444,
        "radius": 0.625,
        "flying": False,
    },
    UnitTypeId.HELLIONTANK: {
        "minerals": 100,
        "gas": 0,
        "supply": 2,
        "army_value": 4.444,
        "radius": 0.625,
        "flying": False,
    },
    UnitTypeId.WIDOWMINE: {
        "minerals": 75,
        "gas": 25,
        "supply": 2,
        "army_value": 4.333,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.WIDOWMINEBURROWED: {
        "minerals": 75,
        "gas": 25,
        "supply": 2,
        "army_value": 4.333,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.SIEGETANK: {
        "minerals": 150,
        "gas": 125,
        "supply": 3,
        "army_value": 17.5,
        "radius": 0.875,
        "flying": False,
    },
    UnitTypeId.SIEGETANKSIEGED: {
        "minerals": 150,
        "gas": 125,
        "supply": 3,
        "army_value": 17.5,
        "radius": 0.875,
        "flying": False,
    },
    UnitTypeId.CYCLONE: {
        "minerals": 150,
        "gas": 100,
        "supply": 3,
        "army_value": 16.0,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.THOR: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 64.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.THORAP: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 64.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.VIKINGASSAULT: {
        "minerals": 150,
        "gas": 75,
        "supply": 2,
        "army_value": 9.667,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.VIKINGFIGHTER: {
        "minerals": 150,
        "gas": 75,
        "supply": 2,
        "army_value": 9.667,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.MEDIVAC: {
        "minerals": 100,
        "gas": 100,
        "supply": 2,
        "army_value": 8.444,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.LIBERATOR: {
        "minerals": 150,
        "gas": 150,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.LIBERATORAG: {
        "minerals": 150,
        "gas": 150,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.BANSHEE: {
        "minerals": 150,
        "gas": 100,
        "supply": 3,
        "army_value": 16.0,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.RAVEN: {
        "minerals": 100,
        "gas": 200,
        "supply": 2,
        "army_value": 12.444,
        "radius": 0.625,
        "flying": True,
    },
    UnitTypeId.BATTLECRUISER: {
        "minerals": 400,
        "gas": 300,
        "supply": 6,
        "army_value": 89.333,
        "radius": 1.25,
        "flying": True,
    },
    UnitTypeId.POINTDEFENSEDRONE: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.PROBE: {
        "minerals": 50,
        "gas": 0,
        "supply": 1,
        "army_value": 1.111,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.ZEALOT: {
        "minerals": 100,
        "gas": 0,
        "supply": 2,
        "army_value": 4.444,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.SENTRY: {
        "minerals": 50,
        "gas": 100,
        "supply": 2,
        "army_value": 6.222,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.STALKER: {
        "minerals": 125,
        "gas": 50,
        "supply": 2,
        "army_value": 7.556,
        "radius": 0.625,
        "flying": False,
    },
    UnitTypeId.ADEPT: {
        "minerals": 100,
        "gas": 25,
        "supply": 2,
        "army_value": 5.444,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.ADEPTPHASESHIFT: {
        "minerals": 100,
        "gas": 25,
        "supply": 2,
        "army_value": 5.444,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.HIGHTEMPLAR: {
        "minerals": 50,
        "gas": 150,
        "supply": 2,
        "army_value": 8.222,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.DARKTEMPLAR: {
        "minerals": 125,
        "gas": 125,
        "supply": 2,
        "army_value": 10.556,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.ARCHON: {
        "minerals": 175,
        "gas": 275,
        "supply": 4,
        "army_value": 37.556,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.OBSERVER: {
        "minerals": 25,
        "gas": 75,
        "supply": 1,
        "army_value": 2.056,
        "radius": 0.5,
        "flying": True,
    },
    UnitTypeId.OBSERVERSIEGEMODE: {
        "minerals": 25,
        "gas": 75,
        "supply": 1,
        "army_value": 2.056,
        "radius": 0.5,
        "flying": True,
    },
    UnitTypeId.WARPPRISM: {
        "minerals": 200,
        "gas": 0,
        "supply": 2,
        "army_value": 8.889,
        "radius": 0.875,
        "flying": True,
    },
    UnitTypeId.WARPPRISMPHASING: {
        "minerals": 200,
        "gas": 0,
        "supply": 2,
        "army_value": 8.889,
        "radius": 0.875,
        "flying": True,
    },
    UnitTypeId.IMMORTAL: {
        "minerals": 275,
        "gas": 100,
        "supply": 4,
        "army_value": 32.444,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.COLOSSUS: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 64.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.DISRUPTOR: {
        "minerals": 150,
        "gas": 150,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.DISRUPTORPHASED: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.PHOENIX: {
        "minerals": 150,
        "gas": 100,
        "supply": 2,
        "army_value": 10.667,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.VOIDRAY: {
        "minerals": 250,
        "gas": 150,
        "supply": 4,
        "army_value": 34.222,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.ORACLE: {
        "minerals": 150,
        "gas": 150,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.75,
        "flying": True,
    },
    UnitTypeId.TEMPEST: {
        "minerals": 250,
        "gas": 175,
        "supply": 5,
        "army_value": 45.278,
        "radius": 1.25,
        "flying": True,
    },
    UnitTypeId.CARRIER: {
        "minerals": 350,
        "gas": 250,
        "supply": 6,
        "army_value": 76.667,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.INTERCEPTOR: {
        "minerals": 15,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.25,
        "flying": True,
    },
    UnitTypeId.MOTHERSHIP: {
        "minerals": 300,
        "gas": 300,
        "supply": 8,
        "army_value": 101.333,
        "radius": 2.75,
        "flying": True,
    },
    UnitTypeId.LARVA: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.125,
        "flying": False,
    },
    UnitTypeId.EGG: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.125,
        "flying": False,
    },
    UnitTypeId.DRONE: {
        "minerals": 50,
        "gas": 0,
        "supply": 1,
        "army_value": 1.111,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.DRONEBURROWED: {
        "minerals": 50,
        "gas": 0,
        "supply": 1,
        "army_value": 1.111,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.QUEEN: {
        "minerals": 150,
        "gas": 0,
        "supply": 2,
        "army_value": 6.667,
        "radius": 0.875,
        "flying": False,
    },
    UnitTypeId.QUEENBURROWED: {
        "minerals": 150,
        "gas": 0,
        "supply": 2,
        "army_value": 6.667,
        "radius": 0.875,
        "flying": False,
    },
    UnitTypeId.ZERGLING: {
        "minerals": 25,
        "gas": 0,
        "supply": 0.5,
        "army_value": 1.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.ZERGLINGBURROWED: {
        "minerals": 25,
        "gas": 0,
        "supply": 0.5,
        "army_value": 1.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.BANELINGCOCOON: {
        "minerals": 25,
        "gas": 25,
        "supply": 0.5,
        "army_value": 0.528,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.BANELING: {
        "minerals": 25,
        "gas": 25,
        "supply": 0.5,
        "army_value": 2.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.BANELINGBURROWED: {
        "minerals": 25,
        "gas": 25,
        "supply": 0.5,
        "army_value": 2.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.ROACH: {
        "minerals": 75,
        "gas": 25,
        "supply": 2,
        "army_value": 4.333,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.ROACHBURROWED: {
        "minerals": 75,
        "gas": 25,
        "supply": 2,
        "army_value": 4.333,
        "radius": 0.5,
        "flying": False,
    },
    UnitTypeId.RAVAGER: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 12.667,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.RAVAGERBURROWED: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 12.667,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.RAVAGERCOCOON: {
        "minerals": 75 + 25,
        "gas": 75 + 25,
        "supply": 3,
        "army_value": 12.667,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.HYDRALISK: {
        "minerals": 100,
        "gas": 50,
        "supply": 2,
        "army_value": 6.444,
        "radius": 0.625,
        "flying": False,
    },
    UnitTypeId.HYDRALISKBURROWED: {
        "minerals": 100,
        "gas": 50,
        "supply": 2,
        "army_value": 6.444,
        "radius": 0.625,
        "flying": False,
    },
    UnitTypeId.LURKERMP: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.LURKERMPBURROWED: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.LURKERMPEGG: {
        "minerals": 50 + 100,
        "gas": 100 + 50,
        "supply": 3,
        "army_value": 19.0,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.INFESTOR: {
        "minerals": 100,
        "gas": 150,
        "supply": 2,
        "army_value": 10.444,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.INFESTEDTERRANSEGG: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.INFESTEDTERRAN: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.INFESTORTERRAN: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.INFESTORBURROWED: {
        "minerals": 100,
        "gas": 150,
        "supply": 2,
        "army_value": 10.444,
        "radius": 0.75,
        "flying": False,
    },
    UnitTypeId.SWARMHOSTMP: {
        "minerals": 100,
        "gas": 75,
        "supply": 3,
        "army_value": 11.167,
        "radius": 0.8125,
        "flying": False,
    },
    UnitTypeId.SWARMHOSTBURROWEDMP: {
        "minerals": 100,
        "gas": 75,
        "supply": 3,
        "army_value": 11.167,
        "radius": 0.8125,
        "flying": False,
    },
    UnitTypeId.LOCUSTMP: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.LOCUSTMPFLYING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 0.375,
        "flying": True,
    },
    UnitTypeId.ULTRALISK: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 64.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.ULTRALISKBURROWED: {
        "minerals": 300,
        "gas": 200,
        "supply": 6,
        "army_value": 64.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.OVERLORD: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.OVERLORDCOCOON: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.OVERLORDTRANSPORT: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.TRANSPORTOVERLORDCOCOON: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.OVERSEER: {
        "minerals": 150,
        "gas": 50,
        "supply": 0,
        "army_value": 2.0,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.OVERSEERSIEGEMODE: {
        "minerals": 150,
        "gas": 50,
        "supply": 0,
        "army_value": 2.0,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.CHANGELING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CHANGELINGMARINE: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CHANGELINGMARINESHIELD: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CHANGELINGZEALOT: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CHANGELINGZERGLING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CHANGELINGZERGLINGWINGS: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.MUTALISK: {
        "minerals": 100,
        "gas": 100,
        "supply": 2,
        "army_value": 8.444,
        "radius": 0.5,
        "flying": True,
    },
    UnitTypeId.CORRUPTOR: {
        "minerals": 150,
        "gas": 100,
        "supply": 2,
        "army_value": 10.667,
        "radius": 0.625,
        "flying": True,
    },
    UnitTypeId.VIPER: {
        "minerals": 100,
        "gas": 200,
        "supply": 3,
        "army_value": 18.667,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.BROODLORD: {
        "minerals": 150 + 150,
        "gas": 150 + 100,
        "supply": 4,
        "army_value": 46.667,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.BROODLORDCOCOON: {
        "minerals": 150 + 150,
        "gas": 150 + 100,
        "supply": 4,
        "army_value": 46.667,
        "radius": 1.0,
        "flying": True,
    },
    UnitTypeId.BROODLING: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 1.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.COMMANDCENTER: {
        "minerals": 400,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": False,
    },
    UnitTypeId.COMMANDCENTERFLYING: {
        "minerals": 400,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": True,
    },
    UnitTypeId.ORBITALCOMMAND: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": True,
    },
    UnitTypeId.ORBITALCOMMANDFLYING: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": True,
    },
    UnitTypeId.PLANETARYFORTRESS: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 25.0,
        "radius": 2.5,
        "flying": False,
    },
    UnitTypeId.SUPPLYDEPOT: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.SUPPLYDEPOTLOWERED: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.REFINERY: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.BARRACKS: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.BARRACKSFLYING: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": True,
    },
    UnitTypeId.ENGINEERINGBAY: {
        "minerals": 125,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.BUNKER: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 15.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.MISSILETURRET: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 5.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.AUTOTURRET: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 3.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.SENSORTOWER: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.FACTORY: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.FACTORYFLYING: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": True,
    },
    UnitTypeId.GHOSTACADEMY: {
        "minerals": 150,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.ARMORY: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.STARPORT: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.STARPORTFLYING: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": True,
    },
    UnitTypeId.FUSIONCORE: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.TECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.BARRACKSTECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.FACTORYTECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.STARPORTTECHLAB: {
        "minerals": 125,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.REACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.BARRACKSREACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.FACTORYREACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.STARPORTREACTOR: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.NEXUS: {
        "minerals": 400,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": False,
    },
    UnitTypeId.PYLON: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.ASSIMILATOR: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.GATEWAY: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.FORGE: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.PHOTONCANNON: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 15.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.SHIELDBATTERY: {
        "minerals": 100,
        "gas": 0,
        "supply": 0,
        "army_value": 10.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.WARPGATE: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.CYBERNETICSCORE: {
        "minerals": 150,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.TWILIGHTCOUNCIL: {
        "minerals": 150,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.ROBOTICSFACILITY: {
        "minerals": 200,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.STARGATE: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.TEMPLARARCHIVE: {
        "minerals": 150,
        "gas": 200,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.DARKSHRINE: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.ROBOTICSBAY: {
        "minerals": 150,
        "gas": 150,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.FLEETBEACON: {
        "minerals": 300,
        "gas": 200,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.ORACLESTASISTRAP: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.HATCHERY: {
        "minerals": 300 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": False,
    },
    UnitTypeId.EXTRACTOR: {
        "minerals": 25 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.SPAWNINGPOOL: {
        "minerals": 200 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.EVOLUTIONCHAMBER: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.SPINECRAWLER: {
        "minerals": 100 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 15.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.SPINECRAWLERUPROOTED: {
        "minerals": 100 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.SPORECRAWLER: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 10.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.SPORECRAWLERUPROOTED: {
        "minerals": 75 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.ROACHWARREN: {
        "minerals": 150 + 50,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.BANELINGNEST: {
        "minerals": 100 + 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.INFESTATIONPIT: {
        "minerals": 150 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.LAIR: {
        "minerals": 450 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": False,
    },
    UnitTypeId.HIVE: {
        "minerals": 650 + 50,
        "gas": 250,
        "supply": 0,
        "army_value": 0.0,
        "radius": 2.5,
        "flying": False,
    },
    UnitTypeId.HYDRALISKDEN: {
        "minerals": 100 + 50,
        "gas": 100,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.LURKERDENMP: {
        "minerals": 150 + 50,
        "gas": 150,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.SPIRE: {
        "minerals": 200 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.NYDUSNETWORK: {
        "minerals": 150 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.NYDUSCANAL: {
        "minerals": 50,
        "gas": 50,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.ULTRALISKCAVERN: {
        "minerals": 150 + 50,
        "gas": 200,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.GREATERSPIRE: {
        "minerals": 300 + 50,
        "gas": 350,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.0,
        "flying": False,
    },
    UnitTypeId.CREEPTUMOR: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CREEPTUMORBURROWED: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.CREEPTUMORQUEEN: {
        "minerals": 0,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 0.375,
        "flying": False,
    },
    UnitTypeId.REFINERYRICH: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.ASSIMILATORRICH: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
    UnitTypeId.EXTRACTORRICH: {
        "minerals": 75,
        "gas": 0,
        "supply": 0,
        "army_value": 0.0,
        "radius": 1.5,
        "flying": False,
    },
}
