from sc2.ids.unit_typeid import UnitTypeId as UnitID

UNIT_TECH_REQUIREMENT: dict[UnitID, list[UnitID]] = dict(
    {
        UnitID.ADEPT: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.ARCHON: [],
        UnitID.BANELING: [UnitID.BANELINGNEST],
        UnitID.BANSHEE: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.STARPORT,
            UnitID.STARPORTTECHLAB,
        ],
        UnitID.BARRACKS: [UnitID.SUPPLYDEPOT],
        UnitID.BATTLECRUISER: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.STARPORT,
            UnitID.STARPORTTECHLAB,
            UnitID.FUSIONCORE,
        ],
        UnitID.BROODLORD: [UnitID.GREATERSPIRE],
        UnitID.CARRIER: [UnitID.STARGATE, UnitID.FLEETBEACON],
        UnitID.COLOSSUS: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
            UnitID.ROBOTICSBAY,
        ],
        UnitID.CORRUPTOR: [UnitID.SPIRE],
        UnitID.CYCLONE: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.DARKTEMPLAR: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.TWILIGHTCOUNCIL,
            UnitID.DARKSHRINE,
        ],
        UnitID.DISRUPTOR: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
            UnitID.ROBOTICSBAY,
        ],
        UnitID.DRONE: [UnitID.HATCHERY],
        UnitID.GHOST: [UnitID.BARRACKS, UnitID.BARRACKSTECHLAB, UnitID.GHOSTACADEMY],
        UnitID.HELLION: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.HELLIONTANK: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.ARMORY],
        UnitID.HIGHTEMPLAR: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.TWILIGHTCOUNCIL,
            UnitID.TEMPLARARCHIVE,
        ],
        UnitID.HYDRALISK: [UnitID.HYDRALISKDEN],
        UnitID.IMMORTAL: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.INFESTOR: [UnitID.INFESTATIONPIT],
        UnitID.LIBERATOR: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.LURKERMP: [UnitID.LURKERDENMP],
        UnitID.MARAUDER: [UnitID.BARRACKS, UnitID.BARRACKSTECHLAB],
        UnitID.MARINE: [UnitID.BARRACKS],
        UnitID.MEDIVAC: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.MOTHERSHIP: [
            UnitID.NEXUS,
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.STARGATE,
            UnitID.FLEETBEACON,
        ],
        UnitID.MUTALISK: [UnitID.SPIRE],
        UnitID.OBSERVER: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.ORACLE: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE, UnitID.STARGATE],
        UnitID.OVERLORD: [UnitID.HATCHERY],
        UnitID.OVERLORDTRANSPORT: [UnitID.LAIR],
        UnitID.OVERSEER: [UnitID.LAIR],
        UnitID.PHOENIX: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE, UnitID.STARGATE],
        UnitID.PROBE: [UnitID.NEXUS],
        UnitID.QUEEN: [UnitID.SPAWNINGPOOL],
        UnitID.RAVAGER: [UnitID.ROACHWARREN],
        UnitID.RAVEN: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.STARPORT,
            UnitID.STARPORTTECHLAB,
        ],
        UnitID.REAPER: [UnitID.BARRACKS],
        UnitID.ROACH: [UnitID.ROACHWARREN],
        UnitID.SCV: [UnitID.COMMANDCENTER],
        UnitID.SENTRY: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.SIEGETANK: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.FACTORYTECHLAB],
        UnitID.STALKER: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.SWARMHOSTMP: [UnitID.INFESTATIONPIT],
        UnitID.TEMPEST: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.STARGATE,
            UnitID.FLEETBEACON,
        ],
        UnitID.THOR: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.FACTORYTECHLAB,
            UnitID.ARMORY,
        ],
        UnitID.ULTRALISK: [UnitID.ULTRALISKCAVERN],
        UnitID.VIKINGFIGHTER: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.VIPER: [UnitID.HIVE],
        UnitID.VOIDRAY: [UnitID.STARGATE],
        UnitID.WARPPRISM: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.WIDOWMINE: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.ZEALOT: [UnitID.GATEWAY],
        UnitID.ZERGLING: [UnitID.SPAWNINGPOOL],
    }
)
