from sc2.ids.unit_typeid import UnitTypeId as UnitID

UNIT_TECH_REQUIREMENT: dict[UnitID, list[UnitID]] = dict(
    {
        # ALL UNITS (structures underneath)
        UnitID.ADEPT: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.ARCHON: [],
        UnitID.BANELING: [UnitID.BANELINGNEST],
        UnitID.BANSHEE: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.STARPORT,
            UnitID.STARPORTTECHLAB,
        ],
        UnitID.BATTLECRUISER: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.STARPORT,
            UnitID.STARPORTTECHLAB,
            UnitID.FUSIONCORE,
        ],
        UnitID.BROODLORD: [UnitID.GREATERSPIRE],
        UnitID.CARRIER: [UnitID.STARGATE, UnitID.FLEETBEACON],
        UnitID.COLOSSUS: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
            UnitID.ROBOTICSBAY,
        ],
        UnitID.CORRUPTOR: [UnitID.SPIRE],
        UnitID.CYCLONE: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.DARKTEMPLAR: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.TWILIGHTCOUNCIL,
            UnitID.DARKSHRINE,
        ],
        UnitID.DISRUPTOR: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
            UnitID.ROBOTICSBAY,
        ],
        UnitID.DRONE: [UnitID.HATCHERY],
        UnitID.GHOST: [UnitID.BARRACKS, UnitID.BARRACKSTECHLAB, UnitID.GHOSTACADEMY],
        UnitID.HELLION: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.HELLIONTANK: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.ARMORY],
        UnitID.HIGHTEMPLAR: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.TWILIGHTCOUNCIL,
            UnitID.TEMPLARARCHIVE,
        ],
        UnitID.HYDRALISK: [UnitID.HYDRALISKDEN],
        UnitID.IMMORTAL: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.INFESTOR: [UnitID.INFESTATIONPIT],
        UnitID.LIBERATOR: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.LURKERMP: [UnitID.LURKERDENMP],
        UnitID.MARAUDER: [UnitID.BARRACKS, UnitID.BARRACKSTECHLAB],
        UnitID.MARINE: [UnitID.BARRACKS],
        UnitID.MEDIVAC: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.MOTHERSHIP: [
            UnitID.NEXUS,
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.STARGATE,
            UnitID.FLEETBEACON,
        ],
        UnitID.MUTALISK: [UnitID.SPIRE],
        UnitID.OBSERVER: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.ORACLE: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE, UnitID.STARGATE],
        UnitID.OVERLORD: [UnitID.HATCHERY],
        UnitID.OVERLORDTRANSPORT: [UnitID.LAIR],
        UnitID.OVERSEER: [UnitID.LAIR],
        UnitID.PHOENIX: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE, UnitID.STARGATE],
        UnitID.PROBE: [UnitID.NEXUS],
        UnitID.QUEEN: [UnitID.SPAWNINGPOOL],
        UnitID.RAVAGER: [UnitID.ROACHWARREN],
        UnitID.RAVEN: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.STARPORT,
            UnitID.STARPORTTECHLAB,
        ],
        UnitID.REAPER: [UnitID.BARRACKS],
        UnitID.ROACH: [UnitID.ROACHWARREN],
        UnitID.SCV: [UnitID.COMMANDCENTER],
        UnitID.SENTRY: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.SIEGETANK: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.FACTORYTECHLAB],
        UnitID.STALKER: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.SWARMHOSTMP: [UnitID.INFESTATIONPIT],
        UnitID.TEMPEST: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.STARGATE,
            UnitID.FLEETBEACON,
        ],
        UnitID.THOR: [
            UnitID.BARRACKS,
            UnitID.FACTORY,
            UnitID.FACTORYTECHLAB,
            UnitID.ARMORY,
        ],
        UnitID.ULTRALISK: [UnitID.ULTRALISKCAVERN],
        UnitID.VIKINGFIGHTER: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.VIPER: [UnitID.HIVE],
        UnitID.VOIDRAY: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE, UnitID.STARGATE],
        UnitID.WARPPRISM: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.WIDOWMINE: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.ZEALOT: [UnitID.GATEWAY],
        UnitID.ZERGLING: [UnitID.SPAWNINGPOOL],
        # ALL STRUCTURES
        # terran
        UnitID.COMMANDCENTER: [],
        UnitID.ORBITALCOMMAND: [UnitID.BARRACKS],
        UnitID.PLANETARYFORTRESS: [UnitID.ENGINEERINGBAY],
        UnitID.SUPPLYDEPOT: [],
        UnitID.REFINERY: [],
        UnitID.REFINERYRICH: [],
        UnitID.BARRACKS: [UnitID.SUPPLYDEPOT],
        UnitID.ENGINEERINGBAY: [UnitID.COMMANDCENTER],
        UnitID.MISSILETURRET: [UnitID.ENGINEERINGBAY],
        UnitID.BUNKER: [UnitID.BARRACKS],
        UnitID.SENSORTOWER: [UnitID.ENGINEERINGBAY],
        UnitID.FACTORY: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.ARMORY: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.STARPORT: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.FUSIONCORE: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.GHOSTACADEMY: [UnitID.BARRACKS],
        UnitID.BARRACKSTECHLAB: [UnitID.BARRACKS],
        UnitID.BARRACKSREACTOR: [UnitID.BARRACKS],
        UnitID.FACTORYTECHLAB: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.FACTORYREACTOR: [UnitID.BARRACKS, UnitID.FACTORY],
        UnitID.STARPORTTECHLAB: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        UnitID.STARPORTREACTOR: [UnitID.BARRACKS, UnitID.FACTORY, UnitID.STARPORT],
        # protoss
        UnitID.NEXUS: [],
        UnitID.PYLON: [],
        UnitID.ASSIMILATOR: [],
        UnitID.ASSIMILATORRICH: [],
        UnitID.GATEWAY: [UnitID.PYLON, UnitID.NEXUS],
        UnitID.CYBERNETICSCORE: [UnitID.GATEWAY],
        UnitID.FORGE: [UnitID.NEXUS],
        UnitID.PHOTONCANNON: [UnitID.FORGE],
        UnitID.TWILIGHTCOUNCIL: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.STARGATE: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.ROBOTICSFACILITY: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE],
        UnitID.TEMPLARARCHIVE: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.TWILIGHTCOUNCIL,
        ],
        UnitID.DARKSHRINE: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.TWILIGHTCOUNCIL,
        ],
        UnitID.ROBOTICSBAY: [
            UnitID.GATEWAY,
            UnitID.CYBERNETICSCORE,
            UnitID.ROBOTICSFACILITY,
        ],
        UnitID.FLEETBEACON: [UnitID.GATEWAY, UnitID.CYBERNETICSCORE, UnitID.STARGATE],
        # zerg
        UnitID.HATCHERY: [],
        UnitID.EXTRACTOR: [],
        UnitID.EXTRACTORRICH: [],
        UnitID.SPAWNINGPOOL: [UnitID.HATCHERY],
        UnitID.EVOLUTIONCHAMBER: [UnitID.HATCHERY],
        UnitID.SPORECRAWLER: [UnitID.HATCHERY],
        UnitID.SPINECRAWLER: [UnitID.SPAWNINGPOOL],
        UnitID.ROACHWARREN: [UnitID.SPAWNINGPOOL],
        UnitID.BANELINGNEST: [UnitID.SPAWNINGPOOL],
        UnitID.LAIR: [UnitID.SPAWNINGPOOL, UnitID.HATCHERY],
        UnitID.SPIRE: [UnitID.LAIR],
        UnitID.HYDRALISKDEN: [UnitID.LAIR],
        UnitID.INFESTATIONPIT: [UnitID.LAIR],
        UnitID.NYDUSNETWORK: [UnitID.LAIR],
        UnitID.HIVE: [UnitID.INFESTATIONPIT, UnitID.LAIR],
        UnitID.ULTRALISKCAVERN: [UnitID.HIVE],
        UnitID.GREATERSPIRE: [UnitID.HIVE, UnitID.SPIRE],
        UnitID.LURKERDENMP: [UnitID.LAIR, UnitID.HYDRALISKDEN],
    }
)
