from __future__ import annotations

from sc2.ids.unit_typeid import UnitTypeId

UNIT_TECH_REQUIREMENT: dict[UnitTypeId, list[UnitTypeId]] = dict(
    {
        # ALL UNITS (structures underneath)
        UnitTypeId.ADEPT: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.ARCHON: [],
        UnitTypeId.BANELING: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.BANELINGNEST],
        UnitTypeId.BANSHEE: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
            UnitTypeId.STARPORTTECHLAB,
        ],
        UnitTypeId.BATTLECRUISER: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
            UnitTypeId.STARPORTTECHLAB,
            UnitTypeId.FUSIONCORE,
        ],
        UnitTypeId.BROODLORD: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
            UnitTypeId.HIVE,
            UnitTypeId.SPIRE,
            UnitTypeId.GREATERSPIRE,
        ],
        UnitTypeId.CARRIER: [UnitTypeId.STARGATE, UnitTypeId.FLEETBEACON],
        UnitTypeId.COLOSSUS: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.ROBOTICSFACILITY,
            UnitTypeId.ROBOTICSBAY,
        ],
        UnitTypeId.CORRUPTOR: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.SPIRE,
        ],
        UnitTypeId.CYCLONE: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.FACTORYTECHLAB,
        ],
        UnitTypeId.DARKTEMPLAR: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.TWILIGHTCOUNCIL,
            UnitTypeId.DARKSHRINE,
        ],
        UnitTypeId.DISRUPTOR: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.ROBOTICSFACILITY,
            UnitTypeId.ROBOTICSBAY,
        ],
        UnitTypeId.DRONE: [UnitTypeId.HATCHERY],
        UnitTypeId.GHOST: [
            UnitTypeId.BARRACKS,
            UnitTypeId.BARRACKSTECHLAB,
            UnitTypeId.GHOSTACADEMY,
        ],
        UnitTypeId.HELLION: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.HELLIONTANK: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.ARMORY,
        ],
        UnitTypeId.HIGHTEMPLAR: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.TWILIGHTCOUNCIL,
            UnitTypeId.TEMPLARARCHIVE,
        ],
        UnitTypeId.HYDRALISK: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.HYDRALISKDEN,
        ],
        UnitTypeId.IMMORTAL: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.ROBOTICSFACILITY,
        ],
        UnitTypeId.INFESTOR: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
        ],
        UnitTypeId.LIBERATOR: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
        ],
        UnitTypeId.LURKERMP: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.HYDRALISKDEN,
            UnitTypeId.LURKERDENMP,
        ],
        UnitTypeId.MARAUDER: [UnitTypeId.BARRACKS, UnitTypeId.BARRACKSTECHLAB],
        UnitTypeId.MARINE: [UnitTypeId.BARRACKS],
        UnitTypeId.MEDIVAC: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
        ],
        UnitTypeId.MOTHERSHIP: [
            UnitTypeId.NEXUS,
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.STARGATE,
            UnitTypeId.FLEETBEACON,
        ],
        UnitTypeId.MUTALISK: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.SPIRE,
        ],
        UnitTypeId.OBSERVER: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.ROBOTICSFACILITY,
        ],
        UnitTypeId.ORACLE: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.STARGATE,
        ],
        UnitTypeId.OVERLORD: [UnitTypeId.HATCHERY],
        UnitTypeId.OVERLORDTRANSPORT: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
        ],
        UnitTypeId.OVERSEER: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
        ],
        UnitTypeId.PHOENIX: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.STARGATE,
        ],
        UnitTypeId.PROBE: [UnitTypeId.NEXUS],
        UnitTypeId.QUEEN: [UnitTypeId.SPAWNINGPOOL],
        UnitTypeId.RAVAGER: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.ROACHWARREN],
        UnitTypeId.RAVEN: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
            UnitTypeId.STARPORTTECHLAB,
        ],
        UnitTypeId.REAPER: [UnitTypeId.BARRACKS],
        UnitTypeId.ROACH: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.ROACHWARREN],
        UnitTypeId.SCV: [UnitTypeId.COMMANDCENTER],
        UnitTypeId.SENTRY: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.SHIELDBATTERY: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.SIEGETANK: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.FACTORYTECHLAB,
        ],
        UnitTypeId.STALKER: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.SWARMHOSTMP: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
        ],
        UnitTypeId.TEMPEST: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.STARGATE,
            UnitTypeId.FLEETBEACON,
        ],
        UnitTypeId.THOR: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.FACTORYTECHLAB,
            UnitTypeId.ARMORY,
        ],
        UnitTypeId.ULTRALISK: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
            UnitTypeId.HIVE,
            UnitTypeId.ULTRALISKCAVERN,
        ],
        UnitTypeId.VIKINGFIGHTER: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
        ],
        UnitTypeId.VIPER: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
            UnitTypeId.HIVE,
        ],
        UnitTypeId.VOIDRAY: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.STARGATE,
        ],
        UnitTypeId.WARPPRISM: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.ROBOTICSFACILITY,
        ],
        UnitTypeId.WIDOWMINE: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.ZEALOT: [UnitTypeId.GATEWAY],
        UnitTypeId.ZERGLING: [UnitTypeId.SPAWNINGPOOL],
        # ALL STRUCTURES
        # terran
        UnitTypeId.COMMANDCENTER: [],
        UnitTypeId.ORBITALCOMMAND: [UnitTypeId.BARRACKS],
        UnitTypeId.PLANETARYFORTRESS: [UnitTypeId.ENGINEERINGBAY],
        UnitTypeId.SUPPLYDEPOT: [],
        UnitTypeId.REFINERY: [],
        UnitTypeId.REFINERYRICH: [],
        UnitTypeId.BARRACKS: [UnitTypeId.SUPPLYDEPOT],
        UnitTypeId.ENGINEERINGBAY: [UnitTypeId.COMMANDCENTER],
        UnitTypeId.MISSILETURRET: [UnitTypeId.ENGINEERINGBAY],
        UnitTypeId.BUNKER: [UnitTypeId.BARRACKS],
        UnitTypeId.SENSORTOWER: [UnitTypeId.ENGINEERINGBAY],
        UnitTypeId.FACTORY: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.ARMORY: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.STARPORT: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.FUSIONCORE: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
        ],
        UnitTypeId.GHOSTACADEMY: [UnitTypeId.BARRACKS],
        UnitTypeId.BARRACKSTECHLAB: [UnitTypeId.BARRACKS],
        UnitTypeId.BARRACKSREACTOR: [UnitTypeId.BARRACKS],
        UnitTypeId.FACTORYTECHLAB: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.FACTORYREACTOR: [UnitTypeId.BARRACKS, UnitTypeId.FACTORY],
        UnitTypeId.STARPORTTECHLAB: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
        ],
        UnitTypeId.STARPORTREACTOR: [
            UnitTypeId.BARRACKS,
            UnitTypeId.FACTORY,
            UnitTypeId.STARPORT,
        ],
        # protoss
        UnitTypeId.NEXUS: [],
        UnitTypeId.PYLON: [],
        UnitTypeId.ASSIMILATOR: [],
        UnitTypeId.ASSIMILATORRICH: [],
        UnitTypeId.GATEWAY: [UnitTypeId.PYLON, UnitTypeId.NEXUS],
        UnitTypeId.CYBERNETICSCORE: [UnitTypeId.GATEWAY],
        UnitTypeId.FORGE: [UnitTypeId.NEXUS],
        UnitTypeId.PHOTONCANNON: [UnitTypeId.FORGE],
        UnitTypeId.TWILIGHTCOUNCIL: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.STARGATE: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.ROBOTICSFACILITY: [UnitTypeId.GATEWAY, UnitTypeId.CYBERNETICSCORE],
        UnitTypeId.TEMPLARARCHIVE: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.TWILIGHTCOUNCIL,
        ],
        UnitTypeId.DARKSHRINE: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.TWILIGHTCOUNCIL,
        ],
        UnitTypeId.ROBOTICSBAY: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.ROBOTICSFACILITY,
        ],
        UnitTypeId.FLEETBEACON: [
            UnitTypeId.GATEWAY,
            UnitTypeId.CYBERNETICSCORE,
            UnitTypeId.STARGATE,
        ],
        # zerg
        UnitTypeId.HATCHERY: [],
        UnitTypeId.EXTRACTOR: [],
        UnitTypeId.EXTRACTORRICH: [],
        UnitTypeId.SPAWNINGPOOL: [UnitTypeId.HATCHERY],
        UnitTypeId.EVOLUTIONCHAMBER: [UnitTypeId.HATCHERY],
        UnitTypeId.SPORECRAWLER: [UnitTypeId.HATCHERY],
        UnitTypeId.SPINECRAWLER: [UnitTypeId.SPAWNINGPOOL],
        UnitTypeId.ROACHWARREN: [UnitTypeId.SPAWNINGPOOL],
        UnitTypeId.BANELINGNEST: [UnitTypeId.SPAWNINGPOOL],
        UnitTypeId.LAIR: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.HATCHERY],
        UnitTypeId.SPIRE: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.LAIR],
        UnitTypeId.HYDRALISKDEN: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.LAIR],
        UnitTypeId.INFESTATIONPIT: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.LAIR],
        UnitTypeId.NYDUSNETWORK: [UnitTypeId.SPAWNINGPOOL, UnitTypeId.LAIR],
        UnitTypeId.HIVE: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
            UnitTypeId.LAIR,
        ],
        UnitTypeId.ULTRALISKCAVERN: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
            UnitTypeId.HIVE,
        ],
        UnitTypeId.GREATERSPIRE: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.INFESTATIONPIT,
            UnitTypeId.HIVE,
            UnitTypeId.SPIRE,
        ],
        UnitTypeId.LURKERDENMP: [
            UnitTypeId.SPAWNINGPOOL,
            UnitTypeId.LAIR,
            UnitTypeId.HYDRALISKDEN,
        ],
    }
)
