UseData: False
Debug: False
GameStep: 2
DebugGameStep: 2

DebugOptions:
    # one of: Air, AirVsGround, Ground, GroundAvoidance, AirAvoidance, GroundToAir
    ActiveGrid: GroundToAir
    ChatDebug: True
    DebugSpawn: False
    ShowPathingCost: False
    ShowBuildingFormation: False
    ResourceDebug: False

Chat:
    Enabled: True
    AiarenaTags: True

Distances:
    FlyingEnemyNearBases: 20.
    GroundEnemyNearBases: 15.
    GroundEnemyLeavingBases: 24.
    FlyingEnemyLeavingBases: 22.

Building:
    # how many seconds before giving up on a construction order?
    CancelOrder: 18

Mining:
    MineralBoost: True
    # shouldn't ever need to turn this off, adds 3-4% income without any tricks
    MineralStacking: True
    # make sure VespeneBoost code is uncommented if setting to True
    VespeneBoost: False
    BoostBackToTownHall: True
    GeyserDistanceFactor: 1.05
    GeyserThreshold: 0.05
    # TODO: Don't think this is used currently, investigate
    #   Seems ResourceManager uses a MINING_RADIUS const instead
    MineralDistanceFactor: 1.25
    TownhallDistanceFactor: 1.08

Pathing:
    # amount of extra buffer to add to unit/structure ranges
    RangeBuffer: 4.0
    EffectsRangeBuffer: 1.0
    CostMultiplier: 1
    # amount of pathing cost to add for each effect and their range
    Effects:
        BlindingCloud:
            Cost: 300
            Range: 3.5
        CorrosiveBile:
            Cost: 100
            Range: 3.0
        KD8Charge:
            Cost: 10
            Range: 4.5
        LiberatorZone:
            Cost: 500
            Range: 6
        LurkerSpine:
            Cost: 600
            Range: 1
        Nuke:
            Cost: 1000
            Range: 8
        ParasiticBomb:
            Cost: 17.15  # roughly 120 / 7
            Range: 4
        Storm:
            Cost: 600
            Range: 3.5

Placement:
    # when requesting a placement, location is locked from being selected
    # this allows the placement to become available again
    WorkerOnRouteTimeout: 60.0
