name: Orchestrator

on:
  push:
    branches:
      - main

jobs:
  call-testing-pipeline:
    name: Testing
    uses: ./.github/workflows/test.yml
  call-linting-pipeline:
    name: Linting
    uses: ./.github/workflows/lint.yml
  call-run-bot-game-pipeline:
    name: Linting
    uses: ./.github/workflows/run_bot_game.yml
  call-release-pipeline:
    name: Release
    needs:
      - call-testing-pipeline
      - call-linting-pipeline
      - call-run-bot-game-pipeline
    uses: ./.github/workflows/release.yml
    secrets: inherit
