name: Deploy Documentation

on:
  release:
    types: [published]

jobs:
  deploy-documentation:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      # install poetry
      - name: Install poetry
        run: pipx install poetry==1.6.1
      # set-up python with cache
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      # install requirements (including dev dependencies)
      - name: Install requirements
        run: poetry install --only docs --no-root
      # build & deploy docs
      - name: Build docs
        run: |
          set -o pipefail
          poetry run make docs-deploy
